FROM python:3.12-slim
RUN python -m venv /opt/poetry \
    && /opt/poetry/bin/pip install --no-cache-dir "poetry>=2.0" \
    && ln -s /opt/poetry/bin/poetry /usr/local/bin/poetry
ENV POETRY_VIRTUALENVS_CREATE=false
LABEL io.deckhouse.internal.builder=true
