FROM registry.deckhouse.io/container-factory@sha256:b9ebf99d849cc88889ee2281f8a9100fdeee4b95b11c4a0350f38135a835f5d1
LABEL io.deckhouse.internal.builder=true
ENV PACKAGES_VERSION=v3.0.2
USER 0
RUN pm install python==3.12.12 && ln -s pip3 /usr/bin/pip
