// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/oci/artifact/store.go
//
// Generated by this command:
//
//	mockgen -source pkg/oci/artifact/store.go -package mock -destination test/mock/artifact_store.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/google/go-containerregistry/pkg/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockStore) Attach(ctx context.Context, parentDigest, artifactType string, payload []byte, checksum, targetPlatform, predicateType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, parentDigest, artifactType, payload, checksum, targetPlatform, predicateType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attach indicates an expected call of Attach.
func (mr *MockStoreMockRecorder) Attach(ctx, parentDigest, artifactType, payload, checksum, targetPlatform, predicateType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockStore)(nil).Attach), ctx, parentDigest, artifactType, payload, checksum, targetPlatform, predicateType)
}

// GetAttached mocks base method.
func (m *MockStore) GetAttached(ctx context.Context, parentDigest, artifactType string, predicateTypes []string) (v1.Descriptor, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttached", ctx, parentDigest, artifactType, predicateTypes)
	ret0, _ := ret[0].(v1.Descriptor)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAttached indicates an expected call of GetAttached.
func (mr *MockStoreMockRecorder) GetAttached(ctx, parentDigest, artifactType, predicateTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttached", reflect.TypeOf((*MockStore)(nil).GetAttached), ctx, parentDigest, artifactType, predicateTypes)
}

// GetAttachedContent mocks base method.
func (m *MockStore) GetAttachedContent(ctx context.Context, parentDigest, artifactType string, predicateTypes []string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachedContent", ctx, parentDigest, artifactType, predicateTypes)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachedContent indicates an expected call of GetAttachedContent.
func (mr *MockStoreMockRecorder) GetAttachedContent(ctx, parentDigest, artifactType, predicateTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachedContent", reflect.TypeOf((*MockStore)(nil).GetAttachedContent), ctx, parentDigest, artifactType, predicateTypes)
}

// GetAttachedContentAny mocks base method.
func (m *MockStore) GetAttachedContentAny(ctx context.Context, parentDigest, artifactType string, predicateTypes []string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachedContentAny", ctx, parentDigest, artifactType, predicateTypes)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachedContentAny indicates an expected call of GetAttachedContentAny.
func (mr *MockStoreMockRecorder) GetAttachedContentAny(ctx, parentDigest, artifactType, predicateTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachedContentAny", reflect.TypeOf((*MockStore)(nil).GetAttachedContentAny), ctx, parentDigest, artifactType, predicateTypes)
}

// GetContentByDigest mocks base method.
func (m *MockStore) GetContentByDigest(ctx context.Context, digest string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContentByDigest", ctx, digest)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContentByDigest indicates an expected call of GetContentByDigest.
func (mr *MockStoreMockRecorder) GetContentByDigest(ctx, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContentByDigest", reflect.TypeOf((*MockStore)(nil).GetContentByDigest), ctx, digest)
}
