FROM debian:bookworm-slim
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      lua5.4 liblua5.4-dev luarocks gcc make ca-certificates \
 && rm -rf /var/lib/apt/lists/*
LABEL io.deckhouse.internal.builder=true
