name: Set up git config
description: Configure the global git user name and email for the current job.
runs:
  using: composite
  steps:
    - name: Set up git config
      run: |
        git config --global user.name "borya"
        git config --global user.email "borya@flant.com"
      shell: bash
