name: tests:all

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [tests:all]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name || 'adhoc' }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: delivery-github-runner
    timeout-minutes: 10
    permissions:
      pull-requests: read
    outputs:
      workflow_proceed: ${{ steps.changes.outputs.workflow_proceed || 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            workflow_proceed:
              - 'go.mod'
              - 'Taskfile.dist.yaml'
              - '.github/**'
              - 'cmd/werf/**'
              - 'pkg/**'
              - 'scripts/**'
              - 'test/**'

  lint:
    if: github.ref == 'refs/heads/main' || needs.detect-changes.outputs.workflow_proceed != 'false'
    needs: detect-changes
    runs-on: delivery-github-runner
    timeout-minutes: 60
    env:
      DEBIAN_FRONTEND: noninteractive
      TASK_X_REMOTE_TASKFILES: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CI base
        uses: ./.github/actions/set-up-ci-base
        with:
          installGolangciLint: "true"

      - name: Lint
        id: lint
        run: task --yes lint

  unit:
    if: github.ref == 'refs/heads/main' || needs.detect-changes.outputs.workflow_proceed != 'false'
    needs:
      - detect-changes
      - lint
    runs-on: delivery-github-runner
    timeout-minutes: 90
    env:
      DEBIAN_FRONTEND: noninteractive
      TASK_X_REMOTE_TASKFILES: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CI base
        uses: ./.github/actions/set-up-ci-base

      - name: Unit tests
        run: task -p --yes test:unit -- --keep-going

  tests:
    if: |
      always() &&
      (github.ref == 'refs/heads/main' || needs.detect-changes.outputs.workflow_proceed != 'false') &&
      needs.lint.result == 'success'
    needs:
      - detect-changes
      - lint
      - unit
    runs-on: delivery-github-runner
    timeout-minutes: 60
    env:
      DEBIAN_FRONTEND: noninteractive
      TASK_X_REMOTE_TASKFILES: 1
      WERF_TEST_K8S_DOCKER_REGISTRY_INSECURE: "false"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up CI base
        uses: ./.github/actions/set-up-ci-base
        with:
          setJobId: "true"
          prepareMultiarch: "true"

      - name: Set up test runtime
        uses: ./.github/actions/set-up-test-runtime
        with:
          coverage: "false"

      - name: Integration tests (main)
        id: integration_main
        continue-on-error: true
        run: |
          task -p --yes test:integration paths="test/legacy_e2e/suites" -- --flake-attempts=3 --keep-going --skip-package 'test/legacy_e2e/suites/deploy,test/legacy_e2e/suites/cleanup_after_converge,test/legacy_e2e/suites/helm/deploy_rollback,test/legacy_e2e/suites/bundles,test/legacy_e2e/suites/ansible,test/legacy_e2e/suites/build/stapel_image/git,test/legacy_e2e/suites/docs,test/legacy_e2e/suites/ansible'
          echo loadavg: $(cat /proc/loadavg)

      - name: E2E tests (simple)
        id: e2e_simple
        continue-on-error: true
        run: |
          task -p --yes test:e2e:simple -- --keep-going
          echo loadavg: $(cat /proc/loadavg)

      - name: E2E tests (complex)
        id: e2e_complex
        continue-on-error: true
        run: |
          task -p --yes test:e2e:complex -- --keep-going
          echo loadavg: $(cat /proc/loadavg)

      - name: E2E tests (extra)
        id: e2e_extra
        continue-on-error: true
        run: |
          task -p --yes test:e2e:extra -- --keep-going
          echo loadavg: $(cat /proc/loadavg)

      - name: Integration tests (git)
        id: integration_git
        continue-on-error: true
        run: |
          task -p --yes test:integration paths="test/legacy_e2e/suites/build/stapel_image/git" -- --flake-attempts=3 --keep-going
          echo loadavg: $(cat /proc/loadavg)

      - name: Finalize test status
        if: always()
        run: |
          echo "integration_main outcome: ${{ steps.integration_main.outcome }}"
          echo "e2e_simple outcome: ${{ steps.e2e_simple.outcome }}"
          echo "e2e_complex outcome: ${{ steps.e2e_complex.outcome }}"
          echo "e2e_extra outcome: ${{ steps.e2e_extra.outcome }}"
          echo "integration_git outcome: ${{ steps.integration_git.outcome }}"

          if [[ "${{ steps.integration_main.outcome }}" == "failure" || \
                "${{ steps.e2e_simple.outcome }}" == "failure" || \
                "${{ steps.e2e_complex.outcome }}" == "failure" || \
                "${{ steps.e2e_extra.outcome }}" == "failure" || \
                "${{ steps.integration_git.outcome }}" == "failure" ]]; then
            echo "One or more test stages failed"
            exit 1
          fi

      - name: Cleanup environment
        if: always()
        run: task --yes test:cleanup:environment

  notify:
    if: |
      always() && (
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false && failure()) ||
      (github.event_name != 'pull_request' && failure())
      )
    needs:
      - lint
      - unit
      - tests
    uses: werf/common-ci/.github/workflows/notification.yml@main
    secrets:
      loopNotificationGroup: ${{ secrets.LOOP_NOTIFICATION_GROUP }}
      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
      notificationChannel: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
